import Head from 'next/head'
import Gmail from '../components/Gmail'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Login from '../components/Login'
import { useEffect, useState } from 'react'

export default function Home() {
  const { data: session } = useSession()


  if (!session) {
    return (
      <Login />
    )
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Gmail />
        </main>
      </div>
    )
  }
}
